version: "0.1"
volume: "D:/tmp/docshell/docs"
service:
  web:
    host: 0.0.0.0
    port: 8080

  db:
    host: 0.0.0.0
    port: 5432
    sslmode: disable

    environment:
      POSTGRES_DB: docshell
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    settings:
      MAX_IDLE_TIME: 5
      MAX_CONN_LIFE: 30
      MAX_OPEN_CONNS: 10
      MAX_IDLE_CONNS: 5
